" Line number
set nu relativenumber

" White space
set bg=dark 
set et ts=4 sts=4 sw=4
set autoindent smartindent smarttab

" Searching
set hls incsearch ignorecase smartcase

" Syntax on
syntax on

" Show matching parenthesis
set showmatch

" Folding
set foldmethod=indent nofoldenable

" Better command line completion
set wildmenu

" Always display status line
set laststatus=2
