" Line number
set nu relativenumber

" White space
set bg=dark 
set et ts=4 sts=4 sw=4
set autoindent smartindent smarttab

" Searching
set hls incsearch ignorecase smartcase

" Syntax on
syntax on

" Show matching parenthesis
set showmatch

" Folding
set foldmethod=indent nofoldenable

" Better command line completion
set wildmenu

" Always display status line
set laststatus=2

call plug#begin('~/.vim/plugged')
    Plug 'preservim/nerdtree'
call plug#end()

" Settings for nerdtree
map <C-n> :NERDTreeToggle<CR>

" Cursor
let &t_SI = "\<Esc>[5 q" " INSERT mode blinking vertical bar
let &t_SR = "\<Esc>[4 q" " REPLACE mode underscore
let &t_EI = "\<Esc>[1 q" " NORMAL mode blinking solid block
